# Data Science Toolbox base install
---
- hosts: 127.0.0.1
  sudo: yes
  connection: local
  tasks:
    - name: Install dst command-line tool
      pip: name=dst state=latest

    - name: Install packages
      apt: pkg={{item}} state=latest
      with_items:
        - git
        - mysql-common
        - libmysqlclient-dev 
        - python-pycurl
        - python-dev
        - python-numpy
        - python-scipy
        - libblas-dev
        - liblapack-dev
        - gfortran

    - name: numpy - upgrade
      pip: name=numpy state=latest

    - name: matplotlib - install
      sudo: yes
      apt: pkg={{ item }} state=latest
      with_items:
        - python-matplotlib
        - libfreetype6-dev
        - libpng12-dev

    - name: Install Python packages
      pip: name={{item}} state=latest
      with_items:
        - pyzmq
        - tornado
        - ipython
        - scikit-learn
        - pandas

    - name: R - add keyserver
      shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

    - name: R - add repo
      apt_repository: repo='deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' state=present

    - name: R - install
      apt: pkg=r-base-dev state=latest update_cache=yes

    - name: Install R packages
      shell: echo "install.packages(c('{{item}}'),repos='http://cran.us.r-project.org')" | R --slave --no-save --no-restore-history
      with_items:
        - ggplot2
        - plyr
        - dplyr
        - lubridate
        - zoo
        - forecast
        - sqldf

    - name: Make sure that the repos directory exists
      file: path=/home/{{ dst_username }}/repos state=directory owner={{ dst_username }} group={{ dst_username }}

    - name: Download bundles
      git: repo=https://github.com/DataScienceToolbox/data-science-toolbox.git dest=/usr/lib/data-science-toolbox
